version: "3.4"
services:
 
  #menu-service
  menu-service:
    container_name: menu-service
    image: greenfield0000/menu-service:1.0.1
    ports:
      - "8082:8082"
      - "9082:9082"
    depends_on:
      - gateway-service

  #journal-service
  journal-service:
    container_name: journal-service
    image: greenfield0000/journal-service:1.0.1
    restart: always
    ports:
      - "8083:8083"
      - "9083:9083"
    depends_on:
      - gateway-service

  # fias-kladr-service
  kladr-service:
    container_name: kladr-service
    restart: always
    image: greenfield0000/kladr-service:1.0.0

  #gateway-service
  gateway-service:
    container_name: gateway-service
    restart: always
    image: greenfield0000/gateway-service:1.0.0
    ports:
      - "8080:8080"
      - "9080:9080"

