version: "3.4"
services:

  #gateway-service
  gateway-service:
    container_name: gateway-service
    restart: always
    image: greenfield0000/gateway-service:1.0.1
    ports:
      - "8080:8080"
      - "9080:9080"
    links:
      - menu-service:menu-service
      - journal-service:journal-service
      - kladr-service:kladr-service

  #auth-service
  auth-service:
    container_name: auth-service
    image: greenfield0000/auth-service:1.0.5
    ports:
      - "8081:8080"
    links:
      - central-db:central-db

  #menu-service
  menu-service:
    container_name: menu-service
    image: greenfield0000/menu-service:1.0.2
    ports:
      - "8082:8082"
      - "9082:9082"
    links:
      - central-db:central-db

  #journal-service
  journal-service:
    container_name: journal-service
    image: greenfield0000/journal-service:1.0.2
    restart: always
    ports:
      - "8083:8083"
      - "9083:9083"
    links:
      - central-db:central-db

  #admin-service
  admin-service:
    container_name: admin-service
    image: greenfield0000/admin-service:1.0.0
    ports:
      - "8084:8080"
    links:
      - central-db:central-db
   
  # fias-kladr-service
  kladr-service:
    container_name: kladr-service
    restart: always
    image: greenfield0000/kladr-service:1.0.1
    ports:
      - "9084:9084"

  central-db:                                                                                                           
    container_name: central-db                                                                                          
    image: postgres:9.6                                                                                                 
    ports:                                                                                                              
      - "5432:5432"                                                                                                     
    environment:                                                                                                        
      - POSTGRES_PASSWORD=admin                                                                                         
      - POSTGRES_USER=admin                                                                                             
      - POSTGRES_DB=central-db                                                                                          
      - PGDATA=/var/lib/postgresql/data/pgdata/central-db
